version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

  backend:
    image: remr-backend-dev:latest
    restart: always
    build:
      context: ./backend
      target: production
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mariadb
      - redis

  frontend:
    image: remr-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mariadb-data:
  redis-data:
