name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Use Yarn 3.6.4 from .yarn/releases
      - name: Install Yarn
        run: yarn install --frozen-lockfile  # Ensure all dependencies are installed

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile  # Ensure all dependencies are installed
      - name: Run Lint
        run: yarn nx affected --target=lint --parallel --base=origin/master --head=HEAD
        working-directory: ./  # Set working directory to the root of your repo

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile  # Ensure all dependencies are installed
      - name: Run Tests for Affected Projects
        run: yarn nx affected --target=test --parallel --base=origin/master --head=HEAD
        working-directory: ./  # Set working directory to the root of your repo

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile  # Ensure all dependencies are installed
      - name: Build Affected Projects
        run: yarn nx affected --target=build --parallel --base=origin/master --head=HEAD
        working-directory: ./  # Set working directory to the root of your repo

  e2e:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile  # Ensure all dependencies are installed
      - name: Run End-to-End Tests
        run: yarn nx affected --target=e2e --parallel --base=origin/master --head=HEAD
        working-directory: ./  # Set working directory to the root of your repo
